version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317"  # OTLP gRPC receiver
      - "4318:4318"  # OTLP HTTP receiver
      - "8889:8889"  # Prometheus metrics exporter port
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./devops/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.29
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # Jaeger gRPC
      - "6831:6831/udp"  # Jaeger UDP port for traces
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3500:3000"  # Grafana web interface
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - otel-collector
      - prometheus
      - jaeger

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9690:9090"
    volumes:
      - ./devops/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'

volumes:
  grafana-storage:
